#!/bin/sh

#export MOZ_ENABLE_WAYLAND=1
#export QT_QPA_PLATFORM=wayland
#export XDG_CURRENT_DESKTOP=river
export XKB_DEFAULT_OPTIONS=caps:swapescape

# The user dbus session is shared across all login sessions and all ttys
# Therefore, only tell it about the first wayland session
if [ "$WAYLAND_DISPLAY" = "wayland-1" ]; then
	dbus-update-activation-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP PATH
fi

timestamp=$(date +%F-%R)
WAYLAND_DEBUG=1 rijan >/tmp/rijan-${timestamp}.log 2>&1 &
#WAYLAND_DEBUG=1 kwm >/tmp/kwm-${timestamp}.log 2>&1 &&
foot --server &
kanshi &
wlsunset -l 48.2 -L 16.4 &
sleep 0.5
swaybg --image ~/Pictures/Backgrounds/everforest/close_up/sakura.png --mode fill &
