# foot.ini

font=Hasklig:size=12

# colors.ini is created/overwritten by local/share/darkman/foot.sh
include=~/.config/foot/colors.ini

[scrollback]
lines=4096

[key-bindings]
#scrollback-up-half-page=Control+u
#scrollback-down-half-page=Control+d
spawn-terminal=none

[cursor]
style=block
blink=no

[bell]
urgent=yes

