# foot.ini

#font=Hasklig:size=12
font=Aporetic Sans Mono:size=12

# darkman.ini is created/overwritten by local/share/darkman/foot.sh
include=~/.config/foot/colors.ini

include=~/.config/foot/themes/dark/ef-owl.ini
include=~/.config/foot/themes/light/modus-operandi.ini

[scrollback]
lines=4096

[key-bindings]
#scrollback-up-half-page=Control+u
#scrollback-down-half-page=Control+d
spawn-terminal=none


[cursor]
style=block
blink=no

[bell]
urgent=yes

