[colors]
background=292c2f    # bg-main
foreground=d0d0d0   # fg-main
regular0=d0d0d0     # "black" fg-main
regular1=d67869     # "red" red
regular2=70bb70     # "green" green
regular3=c09f6f     # "yellow" yellow
regular4=80a4e0     # "blue" blue
regular5=e5a0ea     # "purple" magenta
regular6=8fb8ea     # "cyan" cyan
regular7=4f5f66     # "white" border
bright0=857f8f     # "bright black" fg-dim
bright1=d36d5c     # "bright red" red-intense
bright2=66b666     # "bright green" green-intense
bright3=bc9864     # "bright yellow" yellow-intense
bright4=729add     # "bright blue" blue-intense
bright5=e190e7     # "bright purple" magenta-intense
bright6=7faee7     # "bright cyan" cyan-intense
bright7=60676b     # "bright white" bg-active

# Use operandi bg-yellow-intense for foot's overlay UI elements
# These values seem to apply to both colors and colors2
jump-labels=000000 8f665f
search-box-match=000000 8f665f
urls=8f665f
