# ~/.config/starship.toml

format = "$username in $directory$git_branch$git_status $character"

[username]
show_always = true
style_user = "bold bright-blue"
format = "[$user]($style)"

[directory]
style = "bold bright-green"
format = "[$path]($style)"

[git_branch]
style = "bold #a1cdd8"
format = "[ on $branch]($style)"

[git_status]
style = "#a1cdd8"
format = "([$all_status$ahead_behind]($style))"

[character]
success_symbol = "[λ](bold bright-cyan)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[λ](bold blue)"
