# ~/.config/starship.toml

format = "$username$directory$git_branch$git_status$container $character"

[username]
show_always = true
style_user = "bold bright-blue"
format = "[$user]($style)"

[directory]
style = "bold bright-green"
format = " in [$path]($style)"

[git_branch]
style = "bold #a1cdd8"
format = "[ on $branch]($style)"

[git_status]
style = "#a1cdd8"
modified = '\($count modified\)'
format = "( [$modified]($style))"

[container]
symbol = " ðŸ“¦"
style = "bold yellow"
format = "[$symbol$name]($style)" 

[character]
success_symbol = "[Î»](bold bright-blue)"
error_symbol = "[Î»](bold red)"
vicmd_symbol = "[Î»](bold blue)"
