log_level = "ashell=debug"
outputs = "All"
position = "Top"
enable_esc_key = true

[modules]
left = [ "Workspaces" ]
center = [ "Clock" ]
right = [ ["Privacy", "Settings" ] ]

[appearance]
style="Solid"

background_color="#292c2f"
primary_color="#80a4e0"
secondary_color="#60676b"
text_color = "#d0d0d0" 
workspace_colors = ["#80a4e0"]
