(defun my/shell-command-insert ()
  "Run shell command and insert output at point."
  (interactive)
  (let ((current-prefix-arg '(4)))
    (call-interactively #'shell-command)))

(defun my/meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("!" . my/shell-command-insert)
   '("/" . meow-query-replace)
   '("?" . meow-query-replace-regexp)
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(use-package meow
  :config
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

  (setq meow-use-clipboard t)

  ;; Don't clash with special modes — motion state only (j/k/h/l work, rest is normal Emacs)
  (setq meow-mode-state-list
        '((org-agenda-mode . motion)
          (org-roam-mode . motion)
          (magit-mode . motion)
          (magit-status-mode . motion)
          (magit-log-mode . motion)
          (magit-diff-mode . motion)
          (dired-mode . motion)
          (helpful-mode . motion)
          (help-mode . motion)
          (Info-mode . motion)
          (compilation-mode . motion)
          (messages-buffer-mode . motion)
          (eshell-mode . insert)
          (vterm-mode . insert)
          (term-mode . insert)
	  (eat-mode . insert)
	  (mu4e-main-mode . motion)
	  (mu4e-headers-mode . motion)
	  (mu4e-view-mode . motion)
          (shell-mode . insert)))

; Insert mode in minibuffer (for org-roam-find etc.)
  (add-hook 'minibuffer-setup-hook #'meow-insert-mode)

  (my/meow-setup)
  (meow-global-mode 1))

(provide 'setup-meow)
